theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
max_width = 50
smart_trim = true
hide_when_empty = true
dynamic_width = true
format = "{artist} - {title} "

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "hueshift"
# hue_shifter = "redshift"
# step = 50

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

# [[block]]
# block = "custom"
# command = "echo '{\"text\":\"<big>\ue0b2</big>\",\"color\":\"#DFFF00\"}'"
# # command = "echo '{\"icon\":\"weather_thunder\",\"state\":\"Critical\", \"text\": \"Danger!\"}'"
# json = true
