add_newline = false

format = """
$directory$time$all
"""

[character]
success_symbol = "[-> \\$](bold yellow)"
error_symbol = "[-> \\$](bold blue)"

[status]
disabled = true

[directory]
format = "[\\[$path\\]]($style)[$read_only]($read_only_style) "
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false

[time]
disabled = false

[cmd_duration]
min_time = 0
show_milliseconds = true

[jobs]
disabled = true
