add_newline = false

format = """
$username[@](blue)$hostname $directory$time$all
"""

[character]
success_symbol = "[-> \\$](yellow)"
error_symbol = "[-> \\$](blue)"

[username]
format = "[$user]($style)"
style_user = "bold blue"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold blue"
ssh_only = false

[status]
disabled = true

[directory]
format = "[\\[$path\\]]($style)[$read_only]($read_only_style) "
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false

[time]
disabled = false

[cmd_duration]
min_time = 0
show_milliseconds = true

[jobs]
disabled = true
